# Generated by Django 4.1.2 on 2022-10-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
