# Generated by Django 4.1.2 on 2022-10-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0003_alter_memory_treasure_hunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='clicked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
