# Generated by Django 4.1.2 on 2022-10-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasure_hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasure_hunts.treasurehunt')),
            ],
        ),
    ]
