# Generated by Django 4.1.2 on 2022-10-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure_hunts', '0004_alter_clue_created_at_alter_teamprogress_solved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehunt',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasure_hunts.theme'),
        ),
    ]
