# Generated by Django 4.1.2 on 2022-10-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure_hunts', '0005_alter_treasurehunt_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasure_hunts_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clue',
            name='treasure_hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues_treasure_hunt', to='treasure_hunts.treasurehunt'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='treasure_hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets_treasure_hunt', to='treasure_hunts.treasurehunt'),
        ),
        migrations.AlterField(
            model_name='team',
            name='treasure_hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_treasure_hunt', to='treasure_hunts.treasurehunt'),
        ),
        migrations.AlterField(
            model_name='teamprogress',
            name='clue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress_clue', to='treasure_hunts.clue'),
        ),
        migrations.AlterField(
            model_name='teamprogress',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress_team', to='treasure_hunts.treasurehunt'),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasure_hunts_theme', to='treasure_hunts.theme'),
        ),
    ]
