# Generated by Django 4.1.2 on 2022-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunts', '0006_treasurehunt_created_by_alter_clue_treasure_hunt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
