# Generated by Django 4.1.2 on 2022-10-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunts', '0007_treasurehunt_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprogress',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress_team', to='treasure_hunts.team'),
        ),
    ]
