# Generated by Django 4.1.2 on 2022-10-14 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunts', '0008_alter_teamprogress_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='step_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='team_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='total_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
