# Generated by Django 4.1.2 on 2022-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunts', '0010_treasurehunt_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Allotted'), ('C', 'Cancelled'), ('F', 'Finished')], default='O', max_length=1),
        ),
    ]
